# Generated by Django 4.2.1 on 2023-05-23 09:35

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                null=True, upload_to=user.models.profile_image_file_path
            ),
        ),
    ]
