# Generated by Django 4.2.1 on 2023-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="actors/"
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="directors/"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(
                blank=True, default="no-image.jpg", null=True, upload_to="movies/"
            ),
        ),
        migrations.AlterField(
            model_name="movieframes",
            name="image",
            field=models.ImageField(
                blank=True, default="no-image.jpg", null=True, upload_to="movie_shots/"
            ),
        ),
    ]
