# Generated by Django 4.2.1 on 2023-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_review_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingstar",
            name="value",
            field=models.IntegerField(),
        ),
    ]
